- type: job # goob edit
  id: Passenger
  name: job-name-passenger
  description: job-description-passenger
  playTimeTracker: JobPassenger
  startingGear: PassengerGear
  icon: "JobIconPassenger"
  supervisors: job-supervisors-everyone
  guides: [ Civilian ] # Trauma
  access:
  - Maintenance
  # <Trauma>
  special:
  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - NanoTrasen
      - Assistant
  # </Trauma>
  # mango
    - type: LanguageSpeaker
      speaks:
      - RaiderSpeak
      understands:
      - RaiderSpeak
  # /mango

- type: startingGear
  id: PassengerGear
  equipment:
    id: PassengerPDA
    ears: ClothingHeadsetGrey
  #storage:
    #back:
    #- Stuff

- type: chameleonOutfit
  id: PassengerChameleonOutfit
  job: Passenger
  equipment:
    head: ClothingHeadHatWelding
    eyes: ClothingEyesGlassesCheapSunglasses
    mask: ClothingMaskGas
    neck: ClothingNeckMantle
    outerClothing: ClothingOuterWinterCoat
    gloves: ClothingHandsGlovesColorYellowBudget
